### ISSUE TITLE
Crashes with Biomes O Plenty

### ISSUE THREAD

**Issue by Rikmuld** [Rikmuld/MC-Camping#102]
Crash report:
<details>
---- Minecraft Crash Report ----

WARNING: coremods are present:
OTGCorePlugin (OTG-Core.jar)
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.8.5.jar)
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
FMLPlugin (elulib-0.1.11.jar)
LittlePatchingLoader (LittleTiles v1.5.0-pre66 mc1.12.2.jar)
CreativePatchingLoader (CreativeCore v1.9.15 mc1.12.2.jar)
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
BlurPlugin (Blur-1.0.4-14.jar)
ForgelinPlugin (Forgelin-1.6.0.jar)
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
IvToolkit (IvToolkit-1.3.3-1.12.jar)
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 1/28/18 12:13 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=camping:hemp, properties=[age]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:140)
at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:74)
at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56)
at net.minecraft.block.Block.func_180645_a(Block.java:508)
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
at WorldServerOF.func_72835_b(WorldServerOF.java:37)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:745)

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:140)
at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:74)
at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56)
at net.minecraft.block.Block.func_180645_a(Block.java:508)
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
Level name: LITW-
All players: 1 total; [EntityPlayerMP['SixtyMillionSqrd'/452, l='LITW-', x=53.08, y=63.00, z=-949.29]]
Chunk stats: ServerChunkCache: 935 Drop: 0
Level seed: -7888725893730425113
Level generator: ID 09 - lostcities_bop, ver 0. Features enabled: true
Level generator options: { "profile": "tallbuildings" }
Level spawn location: World: (244,64,216), Chunk: (at 4,4,8 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 247600 game time, 457893 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 85993 (now: false), thunder time: 12186 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3654496520 bytes (3485 MB) / 8556380160 bytes (8160 MB) up to 8589934592 bytes (8192 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
FML: MCP 9.42 Powered by Forge 14.23.1.2560 Optifine OptiFine_1.12.2_HD_U_C8 129 mods loaded, 129 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:--------- |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft | 1.12.2 | minecraft.jar | None |
| UCHIJAAAA | mcp | 9.42 | minecraft.jar | None |
| UCHIJAAAA | FML | 8.0.99.99 | forge-1.12.2-14.23.1.2560.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge | 14.23.1.2560 | forge-1.12.2-14.23.1.2560.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | creativecoredummy | 1.0.0 | minecraft.jar | None |
| UCHIJAAAA | ivtoolkit | 1.3.3-1.12 | minecraft.jar | None |
| UCHIJAAAA | littletilescore | 1.0.0 | minecraft.jar | None |
| UCHIJAAAA | otgcore | 1.12 | minecraft.jar | None |
| UCHIJAAAA | openmodscore | 0.11.4 | minecraft.jar | None |
| UCHIJAAAA | elucore | 1.0 | minecraft.jar | None |
| UCHIJAAAA | mercurius_updater | 1.0 | MercuriusUpdater-1.12.2.jar | None |
| UCHIJAAAA | movillages | 1.5.4 | [1.12]MoVillages-1.5.4.jar | None |
| UCHIJAAAA | aether_legacy | 1.12.2-v2.0 | aether_legacy-1.12.2-v2.0.jar | None |
| UCHIJAAAA | biomesoplenty | 7.0.1.2313 | BiomesOPlenty-1.12.2-7.0.1.2313-universal.jar | None |
| UCHIJAAAA | craftstudioapi | 1.0.0 | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None |
| UCHIJAAAA | animania | 1.4.4 | animania-1.12.2-1.4.4.jar | None |
| UCHIJAAAA | astikoor | 1.0.0 | astikoor-1.0.0.jar | None |
| UCHIJAAAA | astralsorcery | 1.8.5 | astralsorcery-1.12.2-1.8.5.jar | None |
| UCHIJAAAA | atlcraft | MC1.12-Ver1.9 | ATLCraftCandlesMod(MC1.12-Ver1.9).jar | None |
| UCHIJAAAA | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None |
| UCHIJAAAA | enhancedfarming | 1.0.0 | Best Farming - MC 1.12.2 -1.0.0.jar | None |
| UCHIJAAAA | betteragriculture | 1.2.1 | betteragriculture-1.12.2-1.2.1.jar | None |
| UCHIJAAAA | betterfishing | 2.0 | BetterFishing-1.12.2-2.0.jar | None |
| UCHIJAAAA | betterfoliage | 2.1.10 | BetterFoliage-MC1.12-2.1.10.jar | None |
| UCHIJAAAA | betterunderground | 1.0.7 | betterunderground-1.0.7.jar | None |
| UCHIJAAAA | bibliocraft | 2.4.3 | BiblioCraft[v2.4.3][MC1.12.0].jar | None |
| UCHIJAAAA | jei | 4.8.5.138 | jei_1.12.2-4.8.5.138.jar | None |
| UCHIJAAAA | forestry | 5.7.0.238 | forestry_1.12.2-5.7.0.238.jar | None |
| UCHIJAAAA | binniecore | unspecified | binnie-mods-1.12.2-2.5.0.112.jar | None |
| UCHIJAAAA | binniedesign | 1.0 | binnie-mods-1.12.2-2.5.0.112.jar | None |
| UCHIJAAAA | genetics | 2.5.0.112 | binnie-mods-1.12.2-2.5.0.112.jar | None |
| UCHIJAAAA | botany | 2.5.0.112 | binnie-mods-1.12.2-2.5.0.112.jar | None |
| UCHIJAAAA | extrabees | 2.5.0.112 | binnie-mods-1.12.2-2.5.0.112.jar | None |
| UCHIJAAAA | extratrees | 2.5.0.112 | binnie-mods-1.12.2-2.5.0.112.jar | None |
| UCHIJAAAA | blur | 1.0.4-14 | Blur-1.0.4-14.jar | None |
| UCHIJAAAA | bonsaitrees | 1.0.1 | bonsaitrees-1.0.1-b56.jar | None |
| UCHIJAAAA | campfire | 1.2 | campfire-1.12-v1.2.jar | None |
| UCHIJAAAA | chameleon | 1.12-4.1.3 | Chameleon-1.12-4.1.3.jar | None |
| UCHIJAAAA | chickens | 6.0.3 | chickens-6.0.3.jar | None |
| UCHIJAAAA | ctm | MC1.12-0.2.3.9 | CTM-MC1.12-0.2.3.9.jar | None |
| UCHIJAAAA | chisel | MC1.12-0.1.1.26 | Chisel-MC1.12-0.1.1.26.jar | None |
| UCHIJAAAA | chiselsandbits | 14.11 | chiselsandbits-14.11.jar | None |
| UCHIJAAAA | chococraft | 0.9.1.52 | chococraft_1.12.1-0.9.1.52.jar | None |
| UCHIJAAAA | cjcm | 1.0 | cjcm-1.0.jar | None |
| UCHIJAAAA | codechickenlib | 3.1.5.331 | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | cookingforblockheads | 6.3.17 | CookingForBlockheads_1.12.1-6.3.17.jar | None |
| UCHIJAAAA | coralreef | 2.0 | CoralReef-2.2-1.12.2.jar | None |
| UCHIJAAAA | creativecore | 1.9.9 | CreativeCore v1.9.15 mc1.12.2.jar | None |
| UCHIJAAAA | ctdcore | 1.2.2 | CTD-Core-1.12.2-1.2.2.jar | 441b509a0f58a0ef41aca8daf1be20d96287635e |
| UCHIJAAAA | ptrmodellib | 1.0.0 | Decocraft-2.5.2_1.12.2.jar | None |
| UCHIJAAAA | props | 2.5.2 | Decocraft-2.5.2_1.12.2.jar | None |
| UCHIJAAAA | cdm | 0.2.1 | device-mod-0.2.1-1.12.2.jar | None |
| UCHIJAAAA | doggytalents | 1.14.2.314 | DoggyTalents-1.12-1.14.2.314-universal.jar | None |
| UCHIJAAAA | harvestcraft | 1.12.2h | Pam's HarvestCraft 1.12.2h.jar | None |
| UCHIJAAAA | duckcraft | 3.0.8 | Duckcraft-1.12.2-3.0.8.jar | None |
| UCHIJAAAA | dsurround | 3.4.8.5 | DynamicSurroundings-1.12.2-3.4.8.5.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
| UCHIJAAAA | presets | 3.4.8.5 | DynamicSurroundings-1.12.2-3.4.8.5.jar | None |
| UCHIJAAAA | dynamictrees | 1.12.2-0.7.2c | DynamicTrees-1.12.2-0.7.2c.jar | None |
| UCHIJAAAA | earthworks | 1.3.4.3 | Earthworks-1.12-1.3.6.jar | None |
| UCHIJAAAA | ediblebugs | 1.6.0.2512 | ediblebugs-mc1.12.2_eb1.6.0.2512.jar | None |
| UCHIJAAAA | emberroot | 1.3.3 | EmberRootZoo-1.12-1.3.3.jar | None |
| UCHIJAAAA | fairylights | 2.1.2 | fairylights-2.1.2-1.12.x.jar | None |
| UCHIJAAAA | fbp | 2.3.6 | FancyBlockParticles-1.12.x-2.3.6.jar | None |
| UCHIJAAAA | flatcoloredblocks | mc1.12-6.6 | flatcoloredblocks-mc1.12-6.6.jar | None |
| UCHIJAAAA | floricraft | 4.4.1 | Floricraft-1.12.2-4.4.1.jar | None |
| UCHIJAAAA | forgelin | 1.6.0 | Forgelin-1.6.0.jar | None |
| UCHIJAAAA | cfm | 4.1.5 | furniture-4.1.5-1.12.2.jar | None |
| UCHIJAAAA | genera | 1.0.3 | Genera-1.12.2-1.0.3.jar | None |
| UCHIJAAAA | hatchery | 2.0.2 | hatchery-1.12.2-2.0.2.jar | None |
| UCHIJAAAA | waila | 1.8.23 | Hwyla-1.8.23-B38_1.12.jar | None |
| UCHIJAAAA | llibrary | 1.7.9 | llibrary-1.7.9-1.12.jar | None |
| UCHIJAAAA | iceandfire | 1.3.1 | iceandfire-1.3.1-1.12.2.jar | None |
| UCHIJAAAA | ichunutil | 7.1.4 | iChunUtil-1.12.2-7.1.4.jar | None |
| UCHIJAAAA | improvedbackpacks | 1.12-1.1.2.0 | ImprovedBackpacks-1.12-1.1.2.0.jar | None |
| UCHIJAAAA | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| UCHIJAAAA | ironchest | 1.12.2-7.0.34.820 | ironchest-1.12.2-7.0.34.820.jar | None |
| UCHIJAAAA | japaricraftmod | 3.7.0 | japaricraftmod-1.12-3.7.0.jar | None |
| UCHIJAAAA | jeibees | 0.9.0.5 | jeibees-0.9.0.5-mc1.12.2.jar | None |
| UCHIJAAAA | jukebox | 1.2 | jukebox-1.2.jar | None |
| UCHIJAAAA | jaff | 1.7_for_1.12 | JustAFewFish-1.7_for_1.12.jar | None |
| UCHIJAAAA | landlust | 1.12.2-0.3.6 | landlust-1.12.2-0.3.6.jar | None |
| UCHIJAAAA | littletiles | 1.5.0 | LittleTiles v1.5.0-pre66 mc1.12.2.jar | None |
| UCHIJAAAA | lostcities | 1.0.2 | lostcities-1.12-1.0.2.jar | None |
| UCHIJAAAA | lostsouls | 1.1.2 | lostsouls-1.12-1.1.2.jar | None |
| UCHIJAAAA | malisiscore | 1.12.2-6.3.0 | malisiscore-1.12.2-6.3.0.jar | None |
| UCHIJAAAA | malisisdoors | 1.12.2-7.2.2 | malisisdoors-1.12.2-7.2.2.jar | None |
| UCHIJAAAA | radixcore | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None |
| UCHIJAAAA | mca | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar | None |
| UCHIJAAAA | mcmultipart | 2.4.1 | MCMultiPart-2.4.1.jar | None |
| UCHIJAAAA | moglowstone | 1.5.2 | Mo-Glowstone-1.12.2-1.5.2.jar | 1cd8befc36d6dedc5601d77a013f43afc71f899f |
| UCHIJAAAA | moarboats | 1.1.0 | moarboats-1.12.2-1.1.0.jar | None |
| UCHIJAAAA | mobdismemberment | 7.0.0 | MobDismemberment-1.12.2-7.0.0.jar | None |
| UCHIJAAAA | mysticalworld | 0.1.1 | mysticalworld-0.1.1.jar | None |
| UCHIJAAAA | nex | 2.1.14.15 | NetherEx-1.12-2.1.14.15.jar | None |
| UCHIJAAAA | nei | 2.4.1 | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | nutrition | 2.6.0 | Nutrition-1.12.2-2.6.0.jar | None |
| UCHIJAAAA | openmods | 0.11.4 | OpenModsLib-1.12.2-0.11.4.jar | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
| UCHIJAAAA | openblocks | 1.7.4 | OpenBlocks-1.12.2-1.7.4.jar | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
| UCHIJAAAA | packingtape | 0.7.4 | PackingTape-1.12.0-0.7.4.jar | None |
| UCHIJAAAA | llamamilking | 1.12.2b | Pam's Llama Milking 1.12.2b.jar | None |
| UCHIJAAAA | pamscookables | 1.1 | pamscookables-1.1.jar | None |
| UCHIJAAAA | placebo | 1.1.4 | Placebo-1.12.2-1.1.4.jar | None |
| UCHIJAAAA | twilightforest | 3.5.263 | twilightforest-1.12.2-3.5.263-universal.jar | None |
| UCHIJAAAA | plants2 | 2.3.0 | Plants-1.12.2-2.3.0.jar | None |
| UCHIJAAAA | rainboaks | 1.0.4 | RainbowOaks-1.12-1.0.4.jar | None |
| UCHIJAAAA | randomutilities | 5.0.2 | Random Utilities-1.12-5.0.2.jar | None |
| UCHIJAAAA | reccomplex | 1.4.7 | RecurrentComplex-1.4.7.jar | None |
| UCHIJAAAA | reptilemod | 3.8.4 | reptilemod-1.12.2-3.8.4-80.jar | None |
| UCHIJAAAA | roots | 0.104 | roots-2-0.104.jar | None |
| UCHIJAAAA | ropebridge | 2.0.5 | ropebridge-1.12-2.0.7.jar | None |
| UCHIJAAAA | rustic | 0.4.8 | rustic-0.4.8.jar | None |
| UCHIJAAAA | saltmod | 1.12_e_ | SaltyMod_1.12.1_e_.jar | None |
| UCHIJAAAA | shetiphiancore | 3.5.5 | shetiphiancore-1.12.0-3.5.5.jar | None |
| UCHIJAAAA | silentlib | 2.2.16 | SilentLib-1.12-2.2.16-97.jar | None |
| UCHIJAAAA | silentgems | 2.6.7 | SilentsGems-1.12-2.6.7-258.jar | None |
| UCHIJAAAA | skyesdonuts | 1.3.3 | Skye's Donuts 1.3.3 for MC1.12.2.jar | None |
| UCHIJAAAA | spectrite | 1.6.5 | spectrite-1.6.5.jar | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
| UCHIJAAAA | stellarapi | 1.12.2-0.4.2.7 | Stellar API-1.12.2-0.4.2.7.jar | None |
| UCHIJAAAA | storagedrawers | 1.12-5.2.5 | StorageDrawers-1.12.1-5.3.3.jar | None |
| UCHIJAAAA | tt | 1.12 | tacotuesday-1.12-2.0.12.jar | None |
| UCHIJAAAA | terraqueous | 1.4.8 | terraqueous-1.12.0-1.4.8.jar | None |
| UCHIJAAAA | corerm | 1.2h | TheCampingMod_2.3g.jar | None |
| UCHIJAAAA | camping | 2.3g | TheCampingMod_2.3g.jar | None |
| UCHIJAAAA | totemic | 1.12.2-0.9.2 | Totemic-1.12.2-0.9.2.jar | 21d11d7bf4d97b465382a1f95428029aac6daaea |
| UCHIJAAAA | ultimate_unicorn_mod | 1.5.14 | ultimate_unicorn_mod-1.12.2-1.5.14.jar | None |
| UCHIJAAAA | waddles | 0.5.6 | Waddles-1.12.2-0.5.6.jar | None |
| UCHIJAAAA | wearablebackpacks | 3.1.0 | WearableBackpacks-1.12.2-3.1.0.jar | None |
| UCHIJAAAA | xaerominimap | 1.14.5 | Xaeros_Minimap_1.14.5_Forge_1.12.jar | None |
| UCHIJAAAA | elulib | 0.1.11 | elulib-0.1.11.jar | None |

Loaded coremods (and transformers):
OTGCorePlugin (OTG-Core.jar)
com.pg85.otg.forge.asm.OTGClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.5.jar)

DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.8.5.jar)
org.blockartistry.DynSurround.asm.Transformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)

FMLPlugin (elulib-0.1.11.jar)
elucent.elulib.asm.ASMTransformer
LittlePatchingLoader (LittleTiles v1.5.0-pre66 mc1.12.2.jar)
com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore v1.9.15 mc1.12.2.jar)

OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
openmods.core.OpenModsClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.4-14.jar)
com.tterrag.blur.BlurTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)

ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
shetiphian.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)

BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
mods.betterfoliage.loader.BetterFoliageTransformer
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['SixtyMillionSqrd'/452, l='LITW-', x=53.08, y=63.00, z=-949.29]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
OptiFine Version: OptiFine_1.12.2_HD_U_C8
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: Sildurs Vibrant Shaders v1.166 Extreme.zip
OpenGlVersion: 4.6.0 NVIDIA 390.65
OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8
</details>

**Comment by LiskoSlayer63** [comment]
@Rikmuld what kind crash is this? I wanted so much to try this mut my server is using BoP. If this happens when loading new chunks, then it's not a problem because the world is already pre-generated.

I see it says "Exception ticking world", but I still want to hope.

**Comment by Rikmuld** [comment]
Can happen anytime; easy to fix though, next release will have it fixed.

**Comment by wamc2017** [comment]
Hi,

any chance we could get a new version soon? The crashes are kinda annoying... :smile:
Thanks for the mod btw.

Best regards
wamc

**Comment by Rikmuld** [comment]
I'm aiming for somewhere next week
