### ISSUE TITLE
Pouches, Backpacks and Rucksäcke kill my items

### ISSUE THREAD

**Issue by EinDoppelname** [Rikmuld/MC-Camping#105]
Everytime I put items into pouches, backpacks or rucksäcke they appear there. But if I close and then reopen my inventory they are all empty

**Comment by Rikmuld** [comment]
Can you provide a bit more information, I cannot seem to replicate this. Which version and forge version are you using? Did it happen in single player or multiplayer?

**Comment by EinDoppelname** [comment]
I am playing singleplayer with 1.12.2-14.23.1.2555 forge.

**Comment by Rikmuld** [comment]
@warudo89 thanks that makes it clear, easy to fix now :)
