### ISSUE TITLE
Large amounts of Lag 

### ISSUE THREAD

**Issue by Zygus42** [Rikmuld/MC-Camping#106]
TheCampingMod_2.3g
forge-1.12.2-14.23.1.2607-installer-win

Love the items in this mod, but they produce a large amount of lag.  Consider using a mod called LagGoggles to view them yourself.

**Comment by Rikmuld** [comment]
I'm already aware, most of the mod was written without much taught years ago. Some time ago I finally decided to rewrite it all, it will all be fixed once it is done.

**Comment by Rikmuld** [comment]
Interesting tool btw, LagGoggles, makes it really easy to check for lag. Thanks :)

**Comment by Rikmuld** [comment]
Fixed with the recent rewrite of the tile entities, expect a patch this week.
