### ISSUE TITLE
Fire Dyeing crash and server lockup.

### ISSUE THREAD

**Issue by Hawk-v3** [Rikmuld/MC-Camping#118]
One of my players put Rose Petals into a campfire for an advancement.

This has crashed the server, and caused it to lock up on every start. If this isn't from your mod, could you please tell me what's causing it, I'm not thinknig very well at the moment as I'm unwell. Apologies
[crash-2018-04-28_23.13.21-server.txt](https://github.com/Rikmuld/MC-Camping/files/1959269/crash-2018-04-28_23.13.21-server.txt)
[crash-2018-04-28_23.18.25-server.txt](https://github.com/Rikmuld/MC-Camping/files/1959270/crash-2018-04-28_23.18.25-server.txt)

This is running Minecraft 1.12.2, Forge-1.12.2-14.23.3.2673 and Camping Mod 2.4.0, as well as other mods.

**Comment by Rikmuld** [comment]
Sorry to hear. It seems to be due to the camping mod, perhaps in combination with another mod. Could you try updating to 2.4.2 (you seem to be using 2.4.1 at the moment), and see if this fixes the issue (no crash after dyeing/fixes the lockup)?

If not, please let me know then I'll track down the issue and release a patch for it this week.

**Comment by Hawk-v3** [comment]
It didn't work, sadly.
[crash-2018-05-01_02.47.51-server.txt](https://github.com/Rikmuld/MC-Camping/files/1962792/crash-2018-05-01_02.47.51-server.txt)
This is the attempt at world load from the old save.


[crash-2018-05-01_02.54.07-server.txt](https://github.com/Rikmuld/MC-Camping/files/1962793/crash-2018-05-01_02.54.07-server.txt)
This is an entirely new world. Put Rose Red in campfire, flames went briefly red, game froze, crashed.

This is still with the other mods, as I can't find any reference to another mod in the crash trail, but I'll try a blank "forge + camping" world tomorrow.

**Comment by Rikmuld** [comment]
I replicated it, it seems to only happen in a non-development environment. Working on it now.
