### ISSUE TITLE
Mad addon

### ISSUE THREAD

**Issue by JamesPixie** [Rikmuld/MC-Camping#121]
Im using twitch and im trying to download it for a roleplay but the screen shot keeps showing up.
![capture](https://user-images.githubusercontent.com/39540472/40396836-1e9f9350-5dfd-11e8-9c0e-248986e24594.PNG)
but it is saying that, not allowing me to use it, and it is that mod so im wondering if i have to add anything else to the mod pack for it to work.

**Comment by QuantumStatement** [comment]
You should install [Rikmulds Core Mod](https://minecraft.curseforge.com/projects/285473)
