### ISSUE TITLE
java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by erian-7** [Rikmuld/MC-Camping#64]
I see a previous issue of this nature reported as fixed and closed, so I wasn't sure if this should be a new issue or not. This happens sporadically, most often if I teleport into a region that then generates a camp site. Running with RikMuldsCore_1.2c.jar and TheCampingMod_2.2e.jar.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  FairyLightsLoadingPlugin (fairylights-1.2-1.8.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  SmartCorePlugin (SmartMoving-1.8-16.2.jar)
  WallpaperLoadingPlugin (wallpaper-0.9-1.8.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  PlayerAPIPlugin (PlayerAPI-1.8-1.4.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  ItemPatchingLoader (ItemPhysic Full 1.1.4 mc1.8.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  LoadingPlugin (RandomThings-MC1.8-3.5.5.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 10/8/15 8:56 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
    at com.rikmuld.camping.objs.block.Tent.getLightValue(Tent.scala:113)
    at net.minecraft.block.Block.func_176207_c(Block.java:365)
    at net.minecraft.client.renderer.AOFace.updateVertexBrightness(AOFace.java:85)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:150)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:90)
    at net.minecraft.client.renderer.BlockModelRenderer.renderBlockModel(BlockModelRenderer.java:52)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:44)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:34)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
    at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:448)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:178)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.rikmuld.camping.objs.block.Tent.getLightValue(Tent.scala:113)
    at net.minecraft.block.Block.func_176207_c(Block.java:365)
    at net.minecraft.client.renderer.AOFace.updateVertexBrightness(AOFace.java:85)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:150)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:90)

-- Block model being tesselated --
Details:
    Block: minecraft:tallgrass[type=tall_grass]
    Block location: World: (-19676,64,19956), Chunk: (at 4,4,4 in -1230,1247; contains blocks -19680,0,19952 to -19665,255,19967), Region: (-39,38; contains chunks -1248,1216 to -1217,1247, blocks -19968,0,19456 to -19457,255,19967)
    Using AO: true
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.renderBlockModel(BlockModelRenderer.java:52)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:44)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:34)

-- Block being tesselated --
Details:
    Block type: ID #31 (tile.tallgrass // net.minecraft.block.BlockTallGrass)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (-19676,64,19956), Chunk: (at 4,4,4 in -1230,1247; contains blocks -19680,0,19952 to -19665,255,19967), Region: (-39,38; contains chunks -1248,1216 to -1217,1247, blocks -19968,0,19456 to -19457,255,19967)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
    at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:448)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['erian_7'/29940, l='MpServer', x=-19728.35, y=70.00, z=20093.91]]
    Chunk stats: MultiplayerChunkCache: 310, 310
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -354.00,63.00,47.00 - World: (-354,63,47), Chunk: (at 14,3,15 in -23,2; contains blocks -368,0,32 to -353,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 11704109 game time, 11836365 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 96 total; [EntityItemFrame['entity.ItemFrame.name'/29952, l='MpServer', x=-19729.97, y=71.50, z=20097.50], EntityPig['Pig'/29953, l='MpServer', x=-19754.63, y=71.00, z=20091.72], EntitySpider['Spider'/29954, l='MpServer', x=-19724.50, y=12.00, z=20062.50], EntitySkeleton['Skeleton'/29955, l='MpServer', x=-19724.53, y=19.00, z=20052.84], EntitySkeleton['Skeleton'/29956, l='MpServer', x=-19722.34, y=17.00, z=20056.50], EntityButterfly['entity.Butterfly.name'/29957, l='MpServer', x=-19718.25, y=48.78, z=20123.25], EntityButterfly['entity.Butterfly.name'/29958, l='MpServer', x=-19712.77, y=75.53, z=20116.67], EntityButterfly['entity.Butterfly.name'/29959, l='MpServer', x=-19712.04, y=70.28, z=20115.64], EntitySheep['Sheep'/29960, l='MpServer', x=-19749.94, y=71.00, z=20098.06], EntitySheep['Sheep'/29961, l='MpServer', x=-19748.63, y=71.00, z=20098.06], EntitySheep['Sheep'/29962, l='MpServer', x=-19747.09, y=71.00, z=20100.91], EntitySheep['Sheep'/29963, l='MpServer', x=-19749.19, y=72.00, z=20099.75], EntitySheep['Sheep'/29964, l='MpServer', x=-19749.94, y=71.00, z=20100.91], EntitySheep['Sheep'/29965, l='MpServer', x=-19748.22, y=71.00, z=20100.84], EntitySheep['Sheep'/29966, l='MpServer', x=-19749.94, y=71.00, z=20098.06], EntitySheep['Sheep'/29967, l='MpServer', x=-19748.34, y=72.00, z=20099.84], EntitySheep['Sheep'/29968, l='MpServer', x=-19749.94, y=71.00, z=20099.38], EntityPig['Pig'/29969, l='MpServer', x=-19754.28, y=71.00, z=20099.84], EntitySheep['Sheep'/29970, l='MpServer', x=-19747.09, y=71.00, z=20099.13], EntitySheep['Sheep'/29971, l='MpServer', x=-19747.69, y=71.00, z=20098.06], EntityZombie['Zombie'/29972, l='MpServer', x=-19750.13, y=25.00, z=20066.66], EntityBat['Bat'/29973, l='MpServer', x=-19736.34, y=17.84, z=20057.13], EntityBat['Bat'/29974, l='MpServer', x=-19695.31, y=18.94, z=20060.22], EntitySkeleton['Skeleton'/29975, l='MpServer', x=-19703.50, y=36.00, z=20113.50], EntitySkeleton['Skeleton'/29976, l='MpServer', x=-19702.50, y=36.00, z=20112.50], EntityButterfly['entity.Butterfly.name'/29977, l='MpServer', x=-19709.25, y=67.00, z=20118.78], EntitySpider['Spider'/29978, l='MpServer', x=-19692.91, y=38.00, z=20057.50], EntitySpider['Spider'/29979, l='MpServer', x=-19691.03, y=38.69, z=20051.34], EntityZombie['Zombie'/29980, l='MpServer', x=-19687.50, y=46.00, z=20049.50], EntityEnderman['Enderman'/29981, l='MpServer', x=-19691.44, y=37.00, z=20048.81], EntityEnderman['Enderman'/29982, l='MpServer', x=-19686.66, y=39.00, z=20057.78], EntitySheep['Sheep'/29983, l='MpServer', x=-19771.78, y=70.00, z=20092.19], EntitySkeleton['Skeleton'/29984, l='MpServer', x=-19726.13, y=29.00, z=20034.50], EntityZombie['Zombie'/29985, l='MpServer', x=-19727.31, y=18.00, z=20039.28], EntityZombie['Zombie'/29986, l='MpServer', x=-19713.66, y=32.00, z=20044.34], EntitySkeleton['Skeleton'/29987, l='MpServer', x=-19728.59, y=18.00, z=20039.28], EntitySkeleton['Skeleton'/29988, l='MpServer', x=-19728.09, y=32.00, z=20043.50], EntityKeese['Keese'/29989, l='MpServer', x=-19699.25, y=13.10, z=20038.75], EntityKeese['Keese'/29990, l='MpServer', x=-19701.31, y=19.10, z=20032.44], EntityBat['Bat'/29991, l='MpServer', x=-19674.25, y=14.10, z=20107.19], EntityLyrebird['Lyrebird'/29992, l='MpServer', x=-19683.75, y=71.00, z=20038.94], EntityItem['item.item.lyrebird_egg'/29993, l='MpServer', x=-19684.50, y=71.00, z=20038.81], EntityKeese['Keese'/30249, l='MpServer', x=-19671.75, y=13.13, z=20144.38], EntitySkeleton['Skeleton'/29994, l='MpServer', x=-19672.50, y=15.00, z=20112.50], EntityKeese['Keese'/30250, l='MpServer', x=-19672.25, y=12.00, z=20140.00], EntityCreeper['Creeper'/29995, l='MpServer', x=-19664.72, y=23.00, z=20113.28], EntitySkeleton['Skeleton'/29996, l='MpServer', x=-19664.50, y=27.00, z=20117.50], EntityKeese['Keese'/29997, l='MpServer', x=-19686.28, y=26.10, z=20137.13], EntityRabbit['Rabbit'/29998, l='MpServer', x=-19790.00, y=69.00, z=20083.63], EntityRabbit['Rabbit'/29999, l='MpServer', x=-19784.16, y=70.00, z=20065.38], EntityKeese['Keese'/30000, l='MpServer', x=-19701.88, y=18.31, z=20030.75], EntityKeese['Keese'/30001, l='MpServer', x=-19766.25, y=24.10, z=20043.63], EntityRabbit['Rabbit'/30002, l='MpServer', x=-19766.56, y=71.00, z=20045.53], EntityCreeper['Creeper'/30003, l='MpServer', x=-19673.03, y=12.00, z=20034.69], EntityLyrebird['Lyrebird'/30004, l='MpServer', x=-19671.88, y=71.00, z=20040.88], EntityItem['item.item.kiwi_egg'/30005, l='MpServer', x=-19784.44, y=71.00, z=20116.50], EntityBat['Bat'/30261, l='MpServer', x=-19677.50, y=44.06, z=20035.59], EntityLyrebird['Lyrebird'/30006, l='MpServer', x=-19791.81, y=72.00, z=20120.50], EntityKiwi['entity.EB_Kiwi.name'/30007, l='MpServer', x=-19784.25, y=71.00, z=20117.41], EntityItem['item.item.lyrebird_egg'/30008, l='MpServer', x=-19791.22, y=71.00, z=20120.88], EntityKeese['Keese'/30009, l='MpServer', x=-19692.56, y=15.10, z=20023.34], EntitySkeleton['Skeleton'/30010, l='MpServer', x=-19663.50, y=27.00, z=20118.50], EntityCreeper['Creeper'/30011, l='MpServer', x=-19663.72, y=23.00, z=20112.28], EntityCreeper['Creeper'/30012, l='MpServer', x=-19683.63, y=26.02, z=20147.47], EntityPig['Pig'/30013, l='MpServer', x=-19782.50, y=77.00, z=20136.13], EntitySkeleton['Skeleton'/30014, l='MpServer', x=-19673.50, y=16.00, z=20157.50], EntityPiranha['Piranha'/30016, l='MpServer', x=-19732.75, y=61.59, z=20169.69], EntityRabbit['Rabbit'/30017, l='MpServer', x=-19798.16, y=71.00, z=20100.69], EntityPig['Pig'/30021, l='MpServer', x=-19758.47, y=64.00, z=20168.75], EntityBat['Bat'/30026, l='MpServer', x=-19657.41, y=14.81, z=20156.41], EntityBat['Bat'/30027, l='MpServer', x=-19795.56, y=38.25, z=20042.56], EntityPlayerSP['erian_7'/29940, l='MpServer', x=-19728.35, y=70.00, z=20093.91], EntitySheep['Sheep'/30037, l='MpServer', x=-19679.47, y=73.00, z=20166.31], EntityButterfly['entity.Butterfly.name'/30296, l='MpServer', x=-19743.50, y=71.00, z=20085.50], EntityButterfly['entity.Butterfly.name'/30297, l='MpServer', x=-19741.50, y=71.03, z=20082.50], EntityButterfly['entity.Butterfly.name'/30298, l='MpServer', x=-19742.50, y=71.08, z=20089.50], EntityButterfly['entity.Butterfly.name'/30299, l='MpServer', x=-19742.50, y=71.03, z=20089.50], EntityCreeper['Creeper'/30044, l='MpServer', x=-19803.31, y=12.00, z=20146.28], EntityButterfly['entity.Butterfly.name'/30300, l='MpServer', x=-19742.50, y=71.03, z=20089.50], EntityZombie['Zombie'/30045, l='MpServer', x=-19651.50, y=32.00, z=20014.50], EntityButterfly['entity.Butterfly.name'/30301, l='MpServer', x=-19742.50, y=71.09, z=20089.50], EntitySkeleton['Skeleton'/30057, l='MpServer', x=-19800.91, y=24.00, z=20173.59], EntityZombie['Zombie'/30058, l='MpServer', x=-19797.50, y=45.00, z=20172.50], EntityCreeper['Creeper'/30059, l='MpServer', x=-19807.69, y=48.00, z=20173.41], EntityUnicorn['entity.unicorn.name'/30060, l='MpServer', x=-19796.69, y=65.00, z=20171.63], EntityItem['item.item.string'/29941, l='MpServer', x=-19731.50, y=70.00, z=20083.44], EntityCentipede['Centipede'/29942, l='MpServer', x=-19730.97, y=73.00, z=20083.44], EntityButterfly['entity.Butterfly.name'/29943, l='MpServer', x=-19732.11, y=70.97, z=20089.32], EntityDog['Packer'/29944, l='MpServer', x=-19731.31, y=69.00, z=20092.72], EntityArmorStand['Armor Stand'/29945, l='MpServer', x=-19723.50, y=74.00, z=20092.50], EntityItem['item.item.bone'/29946, l='MpServer', x=-19727.94, y=71.00, z=20072.38], EntityUnicorn['entity.unicorn.name'/29947, l='MpServer', x=-19725.34, y=69.50, z=20103.31], EntityChicken['Chicken'/29948, l='MpServer', x=-19743.22, y=73.00, z=20106.78], EntityItem['item.item.sulphur'/29949, l='MpServer', x=-19737.31, y=71.00, z=20109.75], EntityChicken['Chicken'/29950, l='MpServer', x=-19743.81, y=73.00, z=20104.88], EntityChicken['Chicken'/29951, l='MpServer', x=-19743.22, y=73.00, z=20104.19]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 618086216 bytes (589 MB) / 1819287552 bytes (1735 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1515 101 mods loaded, 101 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1515.jar) 
    UCHIJA  Forge{11.14.3.1515} [Minecraft Forge](forge-1.8-11.14.3.1515.jar) 
    UCHIJA  Aroma1997Core{1.0.3.4} [Aroma1997Core](Aroma1997Core-1.8-1.0.3.4.jar) 
    UCHIJA  CodeChickenCore{1.0.5.36} [CodeChicken Core](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.104} [Not Enough Items](NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCHIJA  PlayerAPI{1.4} [Player API](minecraft.jar) 
    UCHIJA  SmartCore{1.2.1} [Smart Core](minecraft.jar) 
    UCHIJA  itemphysic{1.1.2} [ItemPhysic](minecraft.jar) 
    UCHIJA  zeldaswordskills{1.8-3.0.3b} [Zelda Sword Skills](1.8-zeldaswordskills-3.0.3b.jar) 
    UCHIJA  ChickenShed{1.1.4} [Chicken Shed]([1.8] ChickenShed %28v1.2.0%29.jar) 
    UCHIJA  bspkrsCore{7.01} [bspkrsCore]([1.8]bspkrsCore-universal-7.01.jar) 
    UCHIJA  Treecapitator{1.8} [Treecapitator]([1.8]Treecapitator-universal-2.0.5.jar) 
    UCHIJA  AnimalsPlus{1.4} [Animals Plus](animalsplus-1.4.jar) 
    UCHIJA  ArchitectureCraft{1.0.0} [ArchitectureCraft](ArchitectureCraft-1.0.0-mc1.8.jar) 
    UCHIJA  Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper](Aroma1997Core-1.8-1.0.3.4.jar) 
    UCHIJA  AutoSapling{1.0} [AutoSapling](AutoSap-MC1.8-1.2.jar) 
    UCHIJA  basemetals{1.4.2} [Base Metals](BaseMetals-1.4.2.jar) 
    UCHIJA  Baubles{1.1.1.0} [Baubles](Baubles-1.8-1.1.1.0.jar) 
    UCHIJA  BetterChests{1.2.0.0} [BetterChests](BetterChests-1.8-1.2.0.0.jar) 
    UCHIJA  XaeroBetterPvP{1.6.3} [Better PVP Mod](BetterPvP_1.6.3_Forge_1.8.jar) 
    UCHIJA  buildingbrickscompatvanilla{1.0.1} [Building Bricks Vanilla Compat](BuildingBricks-1.0.1.jar) 
    UCHIJA  buildingbricks{1.0.1} [Building Bricks](BuildingBricks-1.0.1.jar) 
    UCHIJA  bunkermod{2.0} [Bunkermod](Bunkermod-mc1.8-v2.0.jar) 
    UCHIJA  butterflymania{1.5} [Butterfly Mania](butterflymania-1.8-1.5.jar) 
    UCHIJA  capsule{1.0.2} [Capsule](capsule-1.8-1.0.2.jar) 
    UCHIJA  carvablepumpkins{1.2} [carvablepumpkins](Carvable Pumpkins Mod 1.8.jar) 
    UCHIJA  Chameleon{1.8-0.1.0} [Chameleon](Chameleon-1.8-0.1.0.jar) 
    UCHIJA  cheshirecat{2.7} [Cheshire Cat Builder's Helper](cheshirecat-builders-helper-mc1.8.0-2.7.jar) 
    UCHIJA  chiselsandbits{1.4.1} [Chisels & Bits](chiselsandbits-1.4.1.jar) 
    UCHIJA  convenient_recipes{1.8-1.6} [Convenient Recipes](ConvenientRecipes-1.8-1.6.jar) 
    UCHIJA  cwm{1.8-1.2.1} [Custom Items Mod](cwm-1.8-1.2.1.jar) 
    UCHIJA  lootablebodies{1.3.5} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.3.5.jar) 
    UCHIJA  wonderfulwands{1.7.2} [Wonderful Wands](CyanosWonderfulWands_1.8-1.7.2.jar) 
    UCHIJA  decorationmegapack{1.20} [Decoration Mega Pack](decorationmegapack-1.20-1.8-1450.jar) 
    UCHIJA  doggytalents{v1.9.1g} [Doggy Talents](DoggyTalents-1.8-v1.9.1g-universal.jar) 
    UCHIJA  dlr{2.1.0} [Don's Lightning Rod](Dons Lightning Rod-1.8-2.1.0.jar) 
    UCHIJA  DungeonPack{1.8} [DungeonPack](dungeonpack-1.8.jar) 
    UCHIJA  poweradvantage{1.3.1} [Power Advantage](PowerAdvantage-1.3.1.jar) 
    UCHIJA  electricadvantage{1.0.3} [Electric Advantage](ElectricAdvantage-1.0.3.jar) 
    UCHIJA  eplus{3.1.0a1} [Enchanting Plus](EnchantingPlus-1.8-3.1.0a1.jar) 
    UCHIJA  enderutilities{0.4.0-beta-1a} [Ender Utilities](enderutilities-1.8-0.4.0-beta-1a.jar) 
    UCHIJA  exoticbirds{1.0} [Exotic Birds](Exotic Birds 1.0.2a-1.8.jar) 
    UCHIJA  expandedrailsmod{1.7} [Expanded Rails Mod](ExpandedRailsModv1.7--1.8.jar) 
    UCHIJA  expchest{4.0} [Exp Chest](expchest-4.0.jar) 
    UCHIJA  golems{1.14} [Extra Golems](Extra-Golems[1.8]-1.16.jar) 
    UCHIJA  fairylights{1.2} [Fairy Lights](fairylights-1.2-1.8.jar) 
    UCHIJA  flintmod{1.1} [Flint Instead of Wood](FlintInsteadOfWood[1.8]-1.2.2.jar) 
    UCHIJA  fluxducts{1.0.2} [Flux Ducts](fluxducts-mc1.8-1.0.2.jar) 
    UCHIJA  geoactivity{2.1.1} [GeoActivity](geoactivity-2.1.1.jar) 
    UCHIJA  glass_shards{1.5} [Glass Shards](glass_shards_mc1.8-1.5.jar) 
    UCHIJA  hopperducts{1.4.5} [Hopper Ducts](hopperducts-mc1.8-1.4.5.jar) 
    UCHIJA  samshorsefood{1.8-1.1.2} [Horse Upgrade Food](HorseUpgradeFood-1.8-1.1.2.jar) 
    UCHIJA  ice_shards{1.3} [Ice Shards](ice_shards_mc1.8-1.3.jar) 
    UCHIJA  igneousadditions{1.1} [Igneous Additions](IgneousAdditions-1.1.jar) 
    UCHIJA  InventoryPets{1.3.3} [Inventory Pets](inventorypets-1.8-1.3.3.jar) 
    UCHIJA  inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks](InventoryTweaks-1.59-176.jar) 
    UCHIJA  jrfmoonsensor{v1.8.7-00.02.01 Beta} [Uncle Jeff's Sensors](jrfmoonsensor-1.8.7-00.02.01.jar) 
    UCHIJA  larrysmod{1.06.6} [Larry's Mod](larrysmod-1.06.6-1.8.jar) 
    UCHIJA  latticemod{1.1} [Lattice Mod](latticemod-mc1.8-1.1.jar) 
    UCHIJA  LunatriusCore{1.1.2.28} [LunatriusCore](LunatriusCore-1.8-1.1.2.28-universal.jar) 
    UCHIJA  MapWriter{2.2.5} [MapWriter](MapWriter-1.8-2.2.5.jar) 
    UCHIJA  chef{5.0.1} [Master Chef](Master_Chef_v5.0.2-1.8.jar) 
    UCHIJA  RadixCore{1.8-2.0.5} [RadixCore](RadixCore-1.8-2.0.5-universal.jar) 
    UCHIJA  MCA{1.8-5.0.7.1} [Minecraft Comes Alive](MCA-1.8-5.0.7.1-universal.jar) 
    UCHIJA  mineralogy{2.5.1} [Mineralogy](mineralogy-2.5.1.jar) 
    UCHIJA  MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.8-3.0.10B.jar) 
    UCHIJA  missing_pieces{1.1.0} [Missing Pieces](missingPieces-1.8-1.1.0.jar) 
    UCHIJA  missing_pieces4basemetal{1.1.1} [Missing Pieces4BaseMetal](missing_pieces4basemetals-1.8-1.1.1.jar) 
    UCHIJA  morematerials{1.0.20150301.0} [More Materials](morematerials-1.0.20150615.0-MC1.8-20150614.jar) 
    UCHIJA  wuppy29_nethereye{1.4.2} [Nether Eye](Nether Eye 1.8.0-1.4.2.jar) 
    UCHIJA  oldguns{1.3.0} [Old Guns Mod](oldguns-1.4.0.jar) 
    UCHIJA  pandorasbox{2.1.2} [Pandora's Box](PandorasBox-2.1.2.jar) 
    UCHIJA  plantmegapack{5.10} [Plant Mega Pack](plantmegapack-5.10-1.8-1450.jar) 
    UCHIJA  progressiveautomation{1.6.15} [Progressive Automation](ProgressiveAutomation-1.8-1.6.15.jar) 
    UCHIJA  projectbench{0.5.0} [Project Bench Updated](ProjectBench-Update-1.8-0.5.0.jar) 
    UCHIJA  ProjectE{1.8-PE1.0.1B} [ProjectE](ProjectE-1.8-PE1.0.1B.jar) 
    UCHIJA  RandomThings{3.5.5} [Random Things](RandomThings-MC1.8-3.5.5.jar) 
    UCHIJA  RealisticTorches{1.2.1} [Realistic Torches](RealisticTorches-1.8-1.2.1.jar) 
    UCHIJA  redstonepaste{1.7.1} [Redstone Paste](redstonepaste-mc1.8-1.7.1.jar) 
    UCHIJA  reptilemod{3.1.0} [Reptile Mod](reptilemod-1.8.0-3.1.0-26.jar) 
    UCHIJA  corerm{1.2c} [RikMuld's Core](RikMuldsCore_1.2c.jar) 
    UCHIJA  roadblock{2.1.5} [Roadblocks](Roadblocks-1.8-2.1.5.jar) 
    UCHIJA  routerreborn{1.2.00Beta1} [Router Reborn](RouterReborn-1.8-2.0.0.1A-Universal.jar) 
    UCHIJA  rpcraft{Beta 1.3 - 1.8.0} [RP Craft](rpcraft-1.4-1.8.0.jar) 
    UCHIJA  AS_Ruins{15.2} [Ruins Spawning System](Ruins-1.8.jar) 
    UCHIJA  Schematica{1.7.7.137} [Schematica](Schematica-1.8-1.7.7.137-universal.jar) 
    UCHIJA  showarmsstand{1.1} [ShowArmsStand](ShowArmsStand-1.8-1.1.jar) 
    UCHIJA  SilentGems{1.8-1.3.1-beta} [Silent's Gems](SilentGems-1.8-1.3.1-82-beta.jar) 
    UCHIJA  SmartMoving{16.2} [Smart Moving](SmartMoving-1.8-16.2.jar) 
    UCHIJA  SmartRender{2.1} [Smart Render](SmartRender-1.8-2.1.jar) 
    UCHIJA  steamadvantage{1.3.5} [Steam Advantage](SteamAdvantage-1.3.5.jar) 
    UCHIJA  StorageDrawers{1.8-2.1.9} [Storage Drawers](StorageDrawers-1.8-2.1.9.jar) 
    UCHIJA  elementsmod{1.0.5} [The Elements Mod](The Elements Mod [1.0.5c] for Minecraft 1.8.jar) 
    UCHIJA  camping{2.2e} [The Camping Mod 2](TheCampingMod_2.2e.jar) 
    UCHIJA  ultimate_unicorn_mod{1.2.6} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!](ultimate_unicorn_mod-1.8-1.2.6.jar) 
    UCHIJA  unlogicii{2.2.1.0} [UnLogic II](UnLogic II 2.2.1.0.jar) 
    UCHIJA  unlogiciivc{1.1} [UnLogic II Version Checker](UnLogic II 2.2.1.0.jar) 
    UCHIJA  Waila{1.6.0_B1} [Waila](Waila-1.6.0_B1_1.8.1.jar) 
    UCHIJA  wallpaper{0.9} [Wallpaper](wallpaper-0.9-1.8.jar) 
    UCHIJA  wildcaves3{1.8} [Wild Caves 3](WildCaves3-0.4.3.7%281.8%29.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
FairyLightsLoadingPlugin (fairylights-1.2-1.8.jar)
  com.pau101.fairylights.core.FairyLightsClassTransformer
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
SmartCorePlugin (SmartMoving-1.8-16.2.jar)
  net.smart.core.SmartCoreTransformer
WallpaperLoadingPlugin (wallpaper-0.9-1.8.jar)
  com.pau101.wallpaper.core.WallpaperClassTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
PlayerAPIPlugin (PlayerAPI-1.8-1.4.jar)
  api.player.forge.PlayerAPITransformer
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)

ItemPatchingLoader (ItemPhysic Full 1.1.4 mc1.8.jar)
  com.creativemd.itemphysic.ItemTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingPlugin (RandomThings-MC1.8-3.5.5.jar)
  lumien.randomthings.asm.ClassTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Launched Version: 1.8-forge1.8-11.14.3.1515
    LWJGL: 2.9.1
    OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Hopper-Ducts-Dokucraft.zip, Progressive-Automation-v3-Dokucraft.zip, Redstone-Paste-v3-Dokucraft.zip, ZeldaSwordSkills-1.8.zip, Sphax_NEI_512x-64x.zip, Mineralogy_high-res.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by Rikmuld** [comment]
Fixed after the update to 1.12.2
