### ISSUE TITLE
Can't eat roasted marshmallows

### ISSUE THREAD

**Issue by wildjinjer** [Rikmuld/MC-Camping#68]
I just downloaded the camping mod for 1.8. I had an issue with making campfires-- the crafting recipes I found on the wiki did not work. I found a triply from you in a thread that so we hat resolved the campfire problem. I can now make a campfire base with four cobblestones in a tilted square arrangement on the crafting table.  
I was able to roast marshmallows on a campfire base with coal in it, but I can't eat them. Any ideas of what is happening?

How do I make other types of campfires? Could I get the version that has deer?

**Comment by Rikmuld** [comment]
You need to be hungry in order to eat roasted marshmellows. 

Take a look at http://wiki.rikmuld.com/wiki/Kit, for making defferent cooking campfire types. A better wiki will be made soon for all information.
