### ISSUE TITLE
Missing tent pegs, hemp, and tents from game

### ISSUE THREAD

**Issue by bearcalledred** [Rikmuld/MC-Camping#70]
Hello,
I love this mod so far but I can't seem to be able to make tent pegs. I have NEI installed and there is no recipe for tent pegs and I can't craft them by putting in the items for the recipe on a crafting table.
I just have the item "Tent 1477:15" but it has no recipe.

I am using version 1.8 of minecraft and 2.2e of the camping mod.

I have just noticed that I also don't have hemp. :\
At least not in creative mode's all items menu. It does show up in NEI though.
For the record, the mods I have installed are: forge, notenoughitems, codechickencore, the camping mod, rikmulds core, no more recipe conflict, decoration mega pack, plant mega pack, MrCrayfish furniture mod, lots of food, and useful food.
Thanks for any help~

**Comment by Rikmuld** [comment]
Probably 'no more recipe conflict' is acting funny, all the recipes are working fine.
