### ISSUE TITLE
com.rikmuld.camping.objs.block.Tent.getLightValue(Tent.scala:113)

### ISSUE THREAD

**Issue by Ravingar** [Rikmuld/MC-Camping#73]
Was cutting down trees right next to a camping tent, this has happened twice and is repeatable. 
[crash-2016-02-03_10.33.29-client.txt](https://github.com/Rikmuld/MC-Camping/files/116006/crash-2016-02-03_10.33.29-client.txt)
[crash-2016-02-03_10.51.58-client.txt](https://github.com/Rikmuld/MC-Camping/files/116007/crash-2016-02-03_10.51.58-client.txt)

There is also an issue when Right clicking on a tent where it will crash the client, if on a Server it will crash and kick all clients from the server, there has been no crash report generated though and am still waiting to get server log files.

**Comment by Ravingar** [comment]
I have just seen this is a duplicate error, and still seems to be going on. Apologies for duplicating.

**Comment by Rikmuld** [comment]
No problem, more crash-reports are always welcome. Just refrencing the other issue so I can actually find this back. 

#63
