### ISSUE TITLE
Still have the backpack after i died

### ISSUE THREAD

**Issue by titi157** [Rikmuld/MC-Camping#75]
Hello, i'm using "The Camping Mod" 1.7.10 version 2.1g on my public "Zombie Survival Adventure" server. I noticed a bug. The bug is that when a player puts his backpack in the Backpack-Slot and dies. He will respawns with the backpack and everything that he puts inside his backpack. In addition, the /clear command has none effect on the inventory of "The Camping Mod".

I hope, you can fix this bug and release an updated version for Minecraft 1.7.10.
Your mod is AWESOME !

Best Regards,
titi157 :)

**Comment by Rikmuld** [comment]
I'm sorry but support for 1.7.10 has dropped; this problem should not occur in the 1.8 version.
