### ISSUE TITLE
Multiplayer Tent Menue

### ISSUE THREAD

**Issue by Heisenberg1979** [Rikmuld/MC-Camping#76]
Hi,
 
first i have to say many thanks for this wonderful mod. It brings a lot of fun on my Server, but i have a little problem.
When i build a tent with chest and bed etc, and after that i right cklick for the tent menu and it opens, but this menu appears to each payer on the server.
 
Do you have any solution or fix for that ?
 
My server run MC 1.8 with forge 11.14.4.1563 !
 
Sorry, i come from germany, my english is not the best....

**Comment by Rikmuld** [comment]
Thanks for reporting, I just fixed the bug.
