### ISSUE TITLE
Backpack/Rut sack issue 

### ISSUE THREAD

**Issue by acp1212** [Rikmuld/MC-Camping#80]
Whenever I try to craft a backpack it is telling me I need a backpack instead of a pouch.... to craft the backpack. Same goes for the rutsack, need a rutsack to craft the rutsack. I am using the latest update.

**Comment by dan-konopka** [comment]
I submitted a pull request I hope fixes this: #81. I changed the two recipes so that in place of themselves, backpacks now require a pouch and rucksacks now require a backpack. I think this is sensible? Let me know!

**Comment by Rikmuld** [comment]
Great, I merged it.
