### ISSUE TITLE
Error with the Camping Mod

### ISSUE THREAD

**Issue by Tiagocardo** [Rikmuld/MC-Camping#82]
I Rik! I love your mod and I think it's awesome. I've been using it for like 1 year, the problem is that now, whenever I start my world, this crash happens because of the mod (just about a week ago). I started installing the newer version but it keeps crashing. I made a thread in the minecraft forum and they said it was because of this mod. I love this mod so could you please see what's wrong?

Here is the crash report:

[spoiler]---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  SmartCorePlugin (SmartCore-1.8-1.1.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  LoadingPlugin (Bloodmoon-1.3.jar)
  DLFMLCorePlugin (DynamicLights-1.8.jar)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  PlayerAPIPlugin (PlayerAPI-1.8-1.1.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
  SpaceCorePlugin (1.8-SpaceCore-0.8.jar)
  MalisisCorePlugin (malisiscore-1.8-1.4.10.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  LoadingPlugin (Fast-Leave-Decay-Mod-1.8.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1505-universal.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 13-06-2016 12:44
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.rikmuld.corerm.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:188)
	at com.rikmuld.corerm.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:188)
	at scala.collection.Iterator$class.find(Iterator.scala:796)
	at scala.collection.AbstractIterator.find(Iterator.scala:1174)
	at scala.collection.IterableLike$class.find(IterableLike.scala:79)
	at scala.collection.AbstractIterable.find(Iterable.scala:54)
	at com.rikmuld.corerm.CoreUtils$InventoryUtils.containsItem(Utils.scala:188)
	at com.rikmuld.camping.Utils$CampingUtils.hasMap(Utils.scala:78)
	at com.rikmuld.camping.EventsC.onOverlayRender(Events.scala:282)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_EventsC_onOverlayRender_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:854)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:298)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:130)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1321)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.rikmuld.corerm.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:188)
	at com.rikmuld.corerm.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:188)
	at scala.collection.Iterator$class.find(Iterator.scala:796)
	at scala.collection.AbstractIterator.find(Iterator.scala:1174)
	at scala.collection.IterableLike$class.find(IterableLike.scala:79)
	at scala.collection.AbstractIterable.find(Iterable.scala:54)
	at com.rikmuld.corerm.CoreUtils$InventoryUtils.containsItem(Utils.scala:188)
	at com.rikmuld.camping.Utils$CampingUtils.hasMap(Utils.scala:78)
	at com.rikmuld.camping.EventsC.onOverlayRender(Events.scala:282)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_EventsC_onOverlayRender_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:854)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:298)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:130)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TiagoCardoso'/1245, l='MpServer', x=8,50, y=65,00, z=8,50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -13,00,64,00,-64,00 - World: (-13,64,-64), Chunk: (at 3,4,0 in -1,-4; contains blocks -16,0,-64 to -1,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TiagoCardoso'/1245, l='MpServer', x=8,50, y=65,00, z=8,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:407)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 351310240 bytes (335 MB) / 1064828928 bytes (1015 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	IntCache: cache: 11, tcache: 0, allocated: 1, tallocated: 105
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_G7 102 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJAAAA	PlayerAPI{1.1} [Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.1} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	SC0_SpaceCore{0.8} [SpaceCore] (1.8-SpaceCore-0.8.jar) 
	UCHIJAAAA	SC0_Wings{1.2.7} [Survival Wings] (1.8-Survival_Wings-1.2.7.jar) 
	UCHIJAAAA	ChickenShed{1.1.4} [Chicken Shed] ([1.8] ChickenShed (v1.2.0).jar) 
	UCHIJAAAA	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAAAA	ArchitectureCraft{1.2.1} [ArchitectureCraft] (ArchitectureCraft-1.2.1-mc1.8.jar) 
	UCHIJAAAA	AutoSapling{1.0} [AutoSapling] (AutoSap-MC1.8-1.2.jar) 
	UCHIJAAAA	BattleTowers{1.5.2} [Battle Towers] (BattleTowers-1.8.jar) 
	UCHIJAAAA	hud{1.3.6} [Better HUD] (Better HUD by NukeDuck [1.8][1.3.6].jar) 
	UCHIJAAAA	bettervillages{0.5} [Better Villages Mod] (Better-Villages-Mod-1.8.jar) 
	UCHIJAAAA	BetterHorseHud{1.0} [Better Horse Hud] (BetterHorseHud-1.8.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1505-universal.jar) 
	UCHIJAAAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-1.3.jar) 
	UCHIJAAAA	Chameleon{1.8-0.1.0} [Chameleon] (Chameleon-1.8-0.1.0.jar) 
	UCHIJAAAA	ChestTransporter{2.1.0} [Chest Transporter] (ChestTransporter-2.1.0-MC1.8.jar) 
	UCHIJAAAA	Chimneys{1.8} [Chimneys] (Chimneys-Mod-1.8.jar) 
	UCHIJAAAA	convenientrecipes{1.8-1.5} [Convenient Recipes] (ConvenientRecipes-1.8-1.5.jar) 
	UCHIJAAAA	CustomSpawner{3.4.0} [DrZhark's CustomSpawner] (Custom-Mob-Spawner-Mod-1.8.jar) 
	UCHIJAAAA	lootablebodies{1.3.6} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.6.jar) 
	UCHIJAAAA	wonderfulwands{1.5.5} [Cyano's Wonderful Wands] (CyanosWonderfulWands-1.5.5.jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.8} [Doomlike Dungeons] (DoomlikeDungeons-1.8.8-MC1.8.jar) 
	UCHIJAAAA	MoCreatures{8.0.1} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-8.0.1.jar) 
	UCHIJAAAA	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	easyBreeding{2.0.3} [Easy Breeding] (Easy-Breeding-Mod-1.8.jar) 
	UCHIJAAAA	easyconfigbutton{1.8-1.0} [EasyConfigButton] (EasyConfigButton-1.0-MC1.8.jar) 
	UCHIJAAAA	net.blacklab.lib{2.0.3} [EBLib] (EBLib-EL2B3-1.8-F1563.jar) 
	UCHIJAAAA	elevatormod{2.1} [Elevator Mod] (Elevator Mod-2.1.jar) 
	UCHIJAAAA	endercrop{1.8.9-1.2} [Ender Crop] (endercrop-1.8-1.3.jar) 
	UCHIJAAAA	enhancedspawnerstwo{0.2} [enhancedspawnerstwo] (Enhanced Spawners 2 - 2.0.jar) 
	UCHIJAAAA	expchest{4.0} [Exp Chest] (expchest-4.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (Fast-Leave-Decay-Mod-1.8.jar) 
	UCHIJAAAA	ftfloocraft{1.8-0.2} [Floocraft] (Floocraft-Mod-1.8.jar) 
	UCHIJAAAA	samsfooddetails{1.8-1.0.0} [Food Details] (FoodDetails-1.8-1.0.0.jar) 
	UCHIJAAAA	fishing{1.4} [Fishing Net Mod] (GiacomosFishingNet1.8-1.4.jar) 
	UCHIJAAAA	foundry{1.3.3} [Giacomo's Foundry] (GiacomosFoundry1.8-1.3.3.jar) 
	UCHIJAAAA	glass_shards{1.5.1} [Glass Shards] (glass_shards_mc1.8-1.5.1.jar) 
	UCHIJAAAA	grapplemod{1.0} [grapplemod] (Grappling-Hook-Mod-1.8.jar) 
	UCHIJAAAA	iChunUtil{5.5.0} [iChunUtil] (iChunUtil-5.5.0.jar) 
	UCHIJAAAA	GravityGun{5.0.0} [GravityGun] (GravityGun-5.0.0.jar) 
	UCHIJAAAA	hgp{Release} [Horizontal Glass Panes] (hgp-1.8-1.0.2-alpha.jar) 
	UCHIJAAAA	hopperducts{1.4.5} [Hopper Ducts] (hopperducts-mc1.8-1.4.5.jar) 
	UCHIJAAAA	ice_shards{1.3} [Ice Shards] (Ice-Shards-Mod-1.8.jar) 
	UCHIJAAAA	improvedHoes{1.1} [ImprovedHoes] (ImprovedHoes-1.8-1.1.jar) 
	UCHIJAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAAAA	IronChest{6.0.107.754} [Iron Chest] (ironchest-1.8-6.0.107.754-universal.jar) 
	UCHIJAAAA	jacb{1.0.1} [JACB] (JACB-1.8-1.0.1.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	latticemod{1.1} [Lattice Mod] (latticemod-mc1.8-1.1.jar) 
	UCHIJAAAA	lucky{6.0.1} [Lucky Block] (LuckyBlock_1-8_v6-0-1.zip) 
	UCHIJAAAA	magicclover{1.8-0.7.2} [Magic Clover] (magicclover-1.8-0.7.2.jar) 
	UCHIJAAAA	malisiscore{1.8-1.4.10} [MalisisCore] (malisiscore-1.8-1.4.10.jar) 
	UCHIJAAAA	malisisblocks{1.8-1.3} [Malisis Blocks] (malisisblocks-1.8-1.3.jar) 
	UCHIJAAAA	malisisdoors{1.8-2.5.4} [MalisisDoors] (malisisdoors-1.8-2.5.4.jar) 
	UCHIJAAAA	RadixCore{1.8-2.1.0} [RadixCore] (RadixCore-1.8-2.1.0-universal.jar) 
	UCHIJAAAA	MCA{1.8-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8-5.1.1.2-universal.jar) 
	UCHIJAAAA	minions{1.9.8} [Minions] (Minions-1.8.jar) 
	UCHIJAAAA	ModUtilsLib{2.0.0} [ModUtilsLib] (ModUtilsLib-1.8.jar) 
	UCHIJAAAA	MoreFurnaces{1.3.11} [More Furnaces] (More-Furnaces-Mod-1.8.jar) 
	UCHIJAAAA	morefuelsmod-1.8.0{1.3.2} [§4§lMore Fuels Mod] (morefuelsmod-1.8.0-v1.3.2.jar) 
	UCHIJAAAA	cfm{3.6} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6(1.8).jar) 
	UCHIJAAAA	MultiPageChest{1.3.5} [Multi Page Chest] (MultiPageChest-1.3.5-MC1.8.jar) 
	UCHIJAAAA	recipehandler{0.3} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.8.X).jar) 
	UCHIJAAAA	papertazermod{1.0} [Papertazers Base Mod] (Papertazers Base Mod-1.0.jar) 
	UCHIJAAAA	parachutemod{3.1.1} [Parachute Mod] (parachutemod-1.8.0-3.1.2-151.jar) 
	UCHIJAAAA	PigManure{1.0.1} [Pig Manure] (pig-manure-1.0.1.jar) 
	UCHIJAAAA	progressiveautomation{1.6.15} [Progressive Automation] (ProgressiveAutomation-1.8-1.6.15.jar) 
	UCHIJAAAA	redstonepaste{1.7.1} [Redstone Paste] (redstonepaste-mc1.8-1.7.1.jar) 
	UCHIJAAAA	corerm{1.2c} [RikMuld's Core] (RikMuldsCore_1.2d.jar) 
	UCHIJAAAA	Roguelike{1.4.4} [Roguelike Dungeons] (RoguelikeDungeons-1.8-1.4.4.jar) 
	UCHIJAAAA	ropebridge{1.1} [Rope Bridge] (RopeBridge-v1.2-mc1.8.8.jar) 
	UCHIJAAAA	AS_Ruins{15.5} [Ruins Spawning System] (Ruins-1.8.jar) 
	UCHIJAAAA	shipwrecks_winslow{1.6.3} [Shipwrecks!] (shipwrecks_winslow-1.8.0-1.6.3.jar) 
	UCHIJAAAA	wuppy29_slimedungeon{1.6.3} [Slime Dungeons] (Slime Dungeon 1.8.0-1.6.3.jar) 
	UCHIJAAAA	chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.8-2.1.jar) 
	UCHIJAAAA	SlimevoidLib{3.0.0.4-beta-1.8} [Slimevoid Library] (SlimevoidLibrary-3.0.0.4-beta-1.8.jar) 
	UCHIJAAAA	SmartMoving{16.0.1} [Smart Moving] (SmartMoving-1.8-16.0.1.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.8-2.1.jar) 
	UCHIJAAAA	smoothbedrock{2.2.0.8} [SmoothBedrock] (SmoothBedrock-1.8-2.2.0.8.jar) 
	UCHIJAAAA	SolarFurnaces{1.1.0} [SolarFurnaces] (Solar Furnaces 1.8.0 Ver. 1.1.zip) 
	UCHIJAAAA	SophisticatedWolves{3.6.0} [SophisticatedWolves] (SophisticatedWolves-3.6.0.jar) 
	UCHIJAAAA	StorageDrawers{1.8-2.1.9} [Storage Drawers] (StorageDrawers-1.8-2.1.9.jar) 
	UCHIJAAAA	camping{2.3b} [The Camping Mod 2] (TheCampingMod_2.3b.jar) 
	UCHIJAAAA	upsizer{1.0} [Up-Sizer] (upsizer-mc1.8-1.0.jar) 
	UCHIJAAAA	VeinMiner{0.30.2_build.unknown} [Vein Miner] (VeinMiner-1.8_0.30.2.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.30.2_build.unknown} [Mod Support] (VeinMiner-1.8_0.30.2.unknown.jar) 
	UCHIJAAAA	WirelessRedstone{2.0.0.1-alpha-1.8} [Wireless Redstone] (WirelessRedstoneCore-2.0.0.1-alpha-1.8.jar) 
	UCHIJAAAA	zombie_steak{1.8-1.0.2} [Zombie Steak] (ZombieSteak-1.8-1.0.2.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
SmartCorePlugin (SmartCore-1.8-1.1.jar)
  net.smart.core.SmartCoreTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
LoadingPlugin (Bloodmoon-1.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
PlayerAPIPlugin (PlayerAPI-1.8-1.1.jar)
  api.player.forge.PlayerAPITransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
SpaceCorePlugin (1.8-SpaceCore-0.8.jar)
  com.spacechase0.minecraft.spacecore.asm.block.BlockDestructionTransformer
  com.spacechase0.minecraft.spacecore.asm.network.PacketInterceptTransformer
  com.spacechase0.minecraft.spacecore.asm.mcp.LoaderModInfoTransformer
  com.spacechase0.minecraft.spacecore.asm.mod.ModInitTransformer
  com.spacechase0.minecraft.spacecore.asm.config.GuiFactoryTransformer
MalisisCorePlugin (malisiscore-1.8-1.4.10.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingPlugin (Fast-Leave-Decay-Mod-1.8.jar)
  lumien.fastleavedecay.asm.ClassTransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1505-universal.jar)
  
	Launched Version: 1.8-forge1.8-11.14.4.1563
	LWJGL: 2.9.1
	OpenGL: Intel(R) Q45/Q43 Express Chipset GL version 2.1.0 - Build 8.15.10.2302, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)[/spoiler]

**Comment by Rikmuld** [comment]
Thanks!

The bug was caused by https://github.com/Rikmuld/MC-RMCore, I just fixed it. I will update soon.

**Comment by Tiagocardo** [comment]
Okayyy, thanks!!
