### ISSUE TITLE
java.lang.NullPointerException: Rendering screen [Jul 23]

### ISSUE THREAD

**Issue by andrewteg** [Rikmuld/MC-Camping#84]
Hi,

I saw this was an issue a few days ago with [#48](https://github.com/Rikmuld/MC-Camping/issues/48) but I just got the download last night with the latest. We're using RikMuldsCore_1.2e-1.10.2.jar and TheCampingMod_2.3d-1.10.2.jar and got the crash report when building and think it was when adding a sleeping bag to a tent. Had placed multiple tents in the game at that point too if helpful.

Here's the crash-report and let me know if I can do anything to help test/debug here:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/23/16 8:16 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at com.rikmuld.camping.inventory.objs.GuiTent.func_73863_a(TentGui.scala:70)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.rikmuld.camping.inventory.objs.GuiTent.func_73863_a(TentGui.scala:70)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)

-- Screen render details --
Details:
    Screen name: com.rikmuld.camping.inventory.objs.GuiTent
    Mouse location: Scaled: (341, 176). Absolute: (683, 352)
    Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['PinkYoshiFan'/167043, l='MpServer', x=-297.70, y=14.00, z=1143.49]]
    Chunk stats: MultiplayerChunkCache: 406, 406
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-574,4,1224), Chunk: (at 2,0,8 in -36,76; contains blocks -576,0,1216 to -561,255,1231), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
    Level time: 5945 game time, 5945 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 67 total; [EntityItem['item.item.carrots'/1322903, l='MpServer', x=-347.98, y=5.00, z=1137.53], EntityItem['item.item.slimeball'/442370, l='MpServer', x=-265.80, y=4.00, z=1127.77], EntitySlime['Slime'/1217177, l='MpServer', x=-223.94, y=4.00, z=1093.51], EntityPlayerSP['PinkYoshiFan'/167043, l='MpServer', x=-297.70, y=14.00, z=1143.49], EntityHorse['Horse'/247314, l='MpServer', x=-366.82, y=4.00, z=1219.79], EntityHorse['Horse'/247317, l='MpServer', x=-256.15, y=4.00, z=1172.57], EntitySheep['Sheep'/247316, l='MpServer', x=-344.60, y=4.00, z=1101.40], EntitySlime['Slime'/1244037, l='MpServer', x=-344.96, y=5.12, z=1141.54], EntityItem['item.item.potatoPoisonous'/1001751, l='MpServer', x=-322.91, y=4.94, z=1149.68], EntitySlime['Slime'/1279371, l='MpServer', x=-349.08, y=5.00, z=1138.12], EntityCow['Cow'/247322, l='MpServer', x=-299.49, y=4.00, z=1156.34], EntityPig['Pig'/247321, l='MpServer', x=-353.50, y=4.00, z=1194.50], EntitySlime['Slime'/1279886, l='MpServer', x=-375.74, y=5.17, z=1099.88], EntityHorse['Horse'/247325, l='MpServer', x=-370.33, y=4.00, z=1128.76], EntitySlime['Slime'/1333174, l='MpServer', x=-374.06, y=4.00, z=1129.05], EntityItem['item.item.seeds'/1234741, l='MpServer', x=-308.49, y=4.00, z=1171.56], EntityVillager['Villager'/233131, l='MpServer', x=-303.65, y=4.00, z=1160.63], EntityVillager['Villager'/233130, l='MpServer', x=-257.94, y=5.00, z=1121.65], EntityVillager['Villager'/233129, l='MpServer', x=-281.36, y=5.00, z=1149.90], EntityVillager['Villager'/232873, l='MpServer', x=-268.50, y=5.00, z=1123.50], EntityVillager['Villager'/233128, l='MpServer', x=-286.68, y=5.00, z=1150.74], EntityVillager['Villager'/232872, l='MpServer', x=-292.50, y=6.00, z=1133.70], EntityVillager['Villager'/229551, l='MpServer', x=-289.30, y=5.00, z=1128.50], EntityVillager['Villager'/229550, l='MpServer', x=-266.50, y=3.94, z=1119.20], EntitySlime['Slime'/1163455, l='MpServer', x=-317.21, y=4.00, z=1099.79], EntityVillager['Villager'/233132, l='MpServer', x=-264.21, y=4.00, z=1148.14], EntityItem['item.item.seeds'/1347003, l='MpServer', x=-326.55, y=5.00, z=1149.03], EntityVillager['Villager'/226355, l='MpServer', x=-319.70, y=5.00, z=1121.30], EntityVillager['Villager'/226354, l='MpServer', x=-312.44, y=4.94, z=1175.35], EntityItem['item.item.potato'/1053601, l='MpServer', x=-344.13, y=4.94, z=1145.37], EntityVillager['Villager'/216113, l='MpServer', x=-347.47, y=4.94, z=1147.37], EntityVillager['Villager'/229553, l='MpServer', x=-290.50, y=6.00, z=1132.67], EntityVillager['Villager'/216112, l='MpServer', x=-304.35, y=3.94, z=1139.50], EntityVillager['Villager'/229552, l='MpServer', x=-290.30, y=5.00, z=1137.70], EntitySlime['Slime'/874302, l='MpServer', x=-312.72, y=5.00, z=1173.95], EntityVillager['Villager'/226358, l='MpServer', x=-325.47, y=5.00, z=1132.39], EntityVillager['Villager'/226357, l='MpServer', x=-305.41, y=4.00, z=1126.49], EntityVillager['Villager'/226356, l='MpServer', x=-307.79, y=5.00, z=1123.58], EntityVillager['Villager'/236477, l='MpServer', x=-254.50, y=5.00, z=1101.27], EntityVillager['Villager'/236476, l='MpServer', x=-269.51, y=4.94, z=1113.88], EntityItem['item.item.seeds'/1229741, l='MpServer', x=-306.85, y=5.00, z=1173.88], EntityItem['item.item.seeds'/1249235, l='MpServer', x=-306.36, y=4.94, z=1169.78], EntityItem['item.item.carrots'/645061, l='MpServer', x=-348.05, y=4.94, z=1132.64], EntitySlime['Slime'/1264990, l='MpServer', x=-308.58, y=4.00, z=1190.01], EntitySlime['Slime'/1352537, l='MpServer', x=-325.24, y=4.00, z=1208.02], EntitySlime['Slime'/1120862, l='MpServer', x=-249.69, y=4.76, z=1131.47], EntitySlime['Slime'/886622, l='MpServer', x=-347.11, y=4.53, z=1191.25], EntityItem['item.item.seeds'/1062084, l='MpServer', x=-343.22, y=5.00, z=1143.79], EntitySlime['Slime'/1374400, l='MpServer', x=-327.53, y=4.14, z=1086.48], EntitySlime['Slime'/891099, l='MpServer', x=-330.98, y=4.75, z=1144.96], EntitySlime['Slime'/1220425, l='MpServer', x=-224.11, y=4.00, z=1105.14], EntitySlime['Slime'/925522, l='MpServer', x=-336.47, y=4.00, z=1077.33], EntitySlime['Slime'/1036114, l='MpServer', x=-319.39, y=4.00, z=1159.02], EntityItem['item.item.potato'/401902, l='MpServer', x=-340.96, y=4.94, z=1149.82], EntitySlime['Slime'/996325, l='MpServer', x=-287.98, y=4.00, z=1134.72], EntityItem['item.item.slimeball'/1002468, l='MpServer', x=-265.89, y=3.94, z=1120.37], EntityVillager['Villager'/222959, l='MpServer', x=-319.70, y=5.00, z=1121.30], EntityVillager['Villager'/222958, l='MpServer', x=-326.17, y=5.00, z=1139.36], EntityVillager['Villager'/222957, l='MpServer', x=-321.56, y=5.00, z=1148.49], EntityItem['item.item.seeds'/1076064, l='MpServer', x=-343.39, y=5.00, z=1147.97], EntityVillager['Villager'/222962, l='MpServer', x=-331.70, y=4.00, z=1143.53], EntityVillager['Villager'/222961, l='MpServer', x=-288.41, y=5.00, z=1151.58], EntitySlime['Slime'/579322, l='MpServer', x=-280.32, y=4.00, z=1138.44], EntityVillager['Villager'/222960, l='MpServer', x=-314.51, y=3.94, z=1124.58], EntitySlime['Slime'/1296359, l='MpServer', x=-326.31, y=4.00, z=1204.17], EntitySlime['Slime'/1374829, l='MpServer', x=-252.50, y=4.00, z=1116.50], EntitySlime['Slime'/1317480, l='MpServer', x=-342.38, y=5.76, z=1141.99]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 340794848 bytes (325 MB) / 728580096 bytes (694 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAAAAAAA mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAA FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAAAAAAAAAAAA Forge{12.18.1.2011} [Minecraft Forge](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAAAAAAAAAAAA corerm{1.2e-1.9.4} [RikMuld's Core](RikMuldsCore_1.2e-1.10.2.jar) 
    UCHIJAAAAAAAAAAAAAA camping{2.3d-1.9.4} [The Camping Mod 2](TheCampingMod_2.3d-1.10.2.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 5500'
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2011
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4331, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
```

**Comment by Rikmuld** [comment]
Fixed after updating to 1.12.2
