### ISSUE TITLE
Help me with installing the mod THE RIGHT WAY

### ISSUE THREAD

**Issue by Riggerman10** [Rikmuld/MC-Camping#85]
In minecraft it says it needs the mod corerm and i have no clue what it is... PLZ HELP

**Comment by Rikmuld** [comment]
The steps to properly install the mod are as follows:

1. On the download page, http://rikmuld.com/camping/download, select your Minecraft version. It defaults to the latest version.
2. Then click the download mod button to download the mod file
3. Also, click the download core button to download the 'corerm' file you are missing
4. Drop both files in your mods folder, the mod should now be installed
