### ISSUE TITLE
The Camping mod 1.10.2 2.3d Duplication

### ISSUE THREAD

**Issue by Rosstail** [Rikmuld/MC-Camping#89]
Hello, One of my friend has found a problem of  duplication of items when we set the gamerule keepInventory: True.

A bag with the stuff fall on the ground when we die but the original is keep.... I think this bug is a no-compatibility with the gamerule... Can you fix that? Because we want use bags, cut and other of this mods but we don't disable the keepinventory, delete the mod or verify everyplayer when the server open :/

Thanks for all!

**Comment by Rikmuld** [comment]
Fixed in c1b8c097adf8e501c2e0c8677a6bdce69bcbee4c
