### ISSUE TITLE
Change Hemp Generation Multiplier causes crash

### ISSUE THREAD

**Issue by frakier** [Rikmuld/MC-Camping#92]
EDIT: Solved my own problem you can close this but leave it for anyone else that stumbles into the same situation if you want.

With only the following mods...
TheCampingMod_2.3d-1.10.2
RikMuldsCore_1.2e-1.10.2
and
Quark-r1.1-70
AutoRegLib-1.0-2 {required by Quark}
and
forge-1.10.2-12.18.3.2254 [need to go back and check with forge-1.10.2-12.18.3.2185]

When trying to set hemp gen to 10
I get the error when creating the world.

[crash-2017-04-03_13.36.35-server.txt](https://github.com/Rikmuld/MC-Camping/files/890865/crash-2017-04-03_13.36.35-server.txt)

Single Player Mode. Windows 10 Running MultiMC.

Well it has something to do with forge-1.10.2-12.18.3.2254. Which only one mod required so I'm dropping back to forge-1.10.2-12.18.3.2185.

For anyone that persists and needs a hack...
In quark.cfg disable the world gen. In camping mod leave hemp gen at default [3].
I did notice other wolrd gen problems with forge-1.10.2-12.18.3.2254

**Comment by frakier** [comment]
With only the following mods...
TheCampingMod_2.3d-1.10.2
RikMuldsCore_1.2e-1.10.2
and
Quark-r1.1-70
AutoRegLib-1.0-2 {required by Quark}
I get the error...
So I need the Camping mod hemp so I fished around in Quark's config file.
changed the revamp stone gen to the following.

"revamp stone gen" {
        B:"Enable Limestone"=false
        B:"Enable Marble"=false

So far it works. I'll play around with it a bit and report back.

**Comment by frakier** [comment]
So my original problem was no hemp and raising the gen rate caused a crash.
Ended up disabling part of Quark and started seeing hemp but there was still some interaction with other mods [worldgen] in respect to the multiplier being other than default [3].

Best balance I have found is...
I completely disabled world gen in Quark B:world=false
Set hemp gen back to the default [finding hemp now]
I'll miss the quark world features but I have a working setup for now.

**Comment by Rikmuld** [comment]
Fixed in cd83563
