### ISSUE TITLE
Core mod cant be downloaded

### ISSUE THREAD

**Issue by FloppyCDdrive** [Rikmuld/MC-Camping#94]
if I try to download the cormod it sends me to the add thing but then the countdown doesen't go on and im not getting to the download :(

**Comment by Rikmuld** [comment]
I'm sorry for the inconvenience, I'll fix it as soon as possible. In the meantime you can download the newest version of the coremod from here: https://rikmuld.xyz/s/WrqcYLb3kl5L8JQ.
