### ISSUE TITLE
[1.12.2] Crash when roasting Marshmallow on a Stick

### ISSUE THREAD

**Issue by MilchLos** [Rikmuld/MC-Camping#98]
Noticed a crash when I tried roasting Marshmallows by pointing it at a lit wooden campfire. 

Tested with latest version of the mod with Forge 14.23.1.2604 with no other mods.

Crashlog: 
[crash-2018-01-27_23.02.15-server.txt](https://github.com/Rikmuld/MC-Camping/files/1670579/crash-2018-01-27_23.02.15-server.txt)

**Comment by Rikmuld** [comment]
Fixed. expect an update later today.
